### ISSUE TITLE
`Could not resolve multipart files: Processing of multipart/form-data request failed. Read timed out ` save errors

### ISSUE THREAD

**Issue by laurenwalker** [NCEAS/metacatui#683]
There have been a few `Could not resolve multipart files: Processing of multipart/form-data request failed. Read timed out ` errors in the new editor, logged in Google Analytics. I believe they have all been experienced by the same user (Vargas). This has happened when trying to upload DataONEObjects and an EML document. 

I'm not certain if this is a Metacat bug or something that can be prevented through MetacatUI.

Tomcat log for EML save error:
```
HTTP Verb: PUT
metacat 20180627-10:12:05: [WARN]: registering ConnectionManager... [org.dataone.client.utils.HttpConnectionMonitorService:addMonitor:65]
original pathInfo: /object/urn:uuid:b5d6a97a-d386-4971-8115-d56fda53e6f3
original requestURI: /metacat/d1/mn/v2/object/urn%3Auuid%3Ab5d6a97a-d386-4971-8115-d56fda53e6f3
stripping /metacat/d1/mn/v2 from requestURI
new pathinfo: /object/urn%3Auuid%3Ab5d6a97a-d386-4971-8115-d56fda53e6f3
After decoded: urn:uuid:b5d6a97a-d386-4971-8115-d56fda53e6f3
metacat 20180627-10:12:12: [ERROR]: D1ResourceHandler: Serializing exception with code 500: Could not resolve multipart files: Read timed out [edu.ucsb.nceas.metacat.restservice.D1ResourceHandler:serializeException:536]
org.dataone.service.exceptions.ServiceFailure: Could not resolve multipart files: Read timed out
	at edu.ucsb.nceas.metacat.restservice.D1ResourceHandler.collectMultipartFiles(D1ResourceHandler.java:353)
	at edu.ucsb.nceas.metacat.restservice.v2.MNResourceHandler.putObject(MNResourceHandler.java:1491)
	at edu.ucsb.nceas.metacat.restservice.v2.MNResourceHandler.handle(MNResourceHandler.java:292)
	at edu.ucsb.nceas.metacat.restservice.D1RestServlet.doPut(D1RestServlet.java:106)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:649)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at edu.ucsb.nceas.metacat.restservice.D1URLFilter.doFilter(D1URLFilter.java:48)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:193)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:313)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by laurenwalker** [comment]
May want to look into Apache configs that can increase the timeout limit for uploads

**Comment by vchendrix** [comment]
@laurenwalker We had a user experience that seems to be a similar issue to this.  Below I have included our user's feedback and what seems to be the corresponding metacat error. 

## User Feedback

> I think this must have been a one-time transfer glitch.
> 
> I understand that trying to save while a file is uploading would cause a problem, but this file failed immediately.   It’s only 1 MB.  The csv files uploaded at same time went fine.  (I’ve uploaded the .csv files again.  No problem.)
> 
> The status info warning showed up immediately (refers to ‘multipart file’ ..null).
> 
> Before trying to save, I uploaded the .pdf file again and it was successful.
> 
> I had saved my previous entries so I didn’t lose any input and just had to reload the 3 .cvs files.
> 
> My concern is that once this failure notice pops up, I couldn’t save the record.  If I had entered all the metadata without saving, and then had this file upload error prevent me from saving, I would be more than mildly annoyed. 
> 
> If the system thinks that a file is taking too long to upload or has failed, could a ‘cancel upload’ popup be added to prevent this lock up and potential loss of entries?
> 

## Metacat Exception
```
metacat 20191025-15:41:02: [ERROR]: D1ResourceHandler: Serializing exception with code 500: Could not resolve multipart files: null [edu.ucsb.nceas.metacat.restservice.D1ResourceHandler:serializeException:536]
org.dataone.service.exceptions.ServiceFailure: Could not resolve multipart files: null
        at edu.ucsb.nceas.metacat.restservice.D1ResourceHandler.collectMultipartFiles(D1ResourceHandler.java:354)
        at edu.ucsb.nceas.metacat.restservice.v2.MNResourceHandler.putObject(MNResourceHandler.java:1571)
        at edu.ucsb.nceas.metacat.restservice.v2.MNResourceHandler.handle(MNResourceHandler.java:291)
        at edu.ucsb.nceas.metacat.restservice.D1RestServlet.doPost(D1RestServlet.java:86)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at edu.ucsb.nceas.metacat.restservice.D1URLFilter.doFilter(D1URLFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:494)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:104)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:1025)
        at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:689)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
        at org.apache.coyote.ajp.AjpAprProcessor.process(AjpAprProcessor.java:188)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
        at org.apache.tomcat.util.net.AprEndpoint$SocketWithOptionsProcessor.run(AprEndpoint.java:2512)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
```
